name: gimmemotifs
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3
  - sphinx_bootstrap_theme
  - numpydoc
  - pypandoc
  - diskcache
  - feather-format
  - future
  - ghostscript
  - jinja2
  - matplotlib >=2.0
  - numpy
  - pillow
  - pyarrow
  - python-xxhash
  - pyyaml >=3.10
  - scikit-learn >=0.18
  - scipy <1.3.0
  - seaborn
  - six
  - sklearn-contrib-lightning
  - statsmodels
  - tqdm
  - xdg
  - xgboost >=0.71
