language: python

python:
  - "2.7"

cache:
  apt: true
#  directories:
#    - $HOME/miniconda

addons:
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - if [ ! -e $HOME/miniconda]; then ./miniconda.sh -b -p $HOME/miniconda; fi
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy matplotlib
  - pip install .
#  - pip install nose coverage
#  - pip install coveralls
# # command to run tests, e.g. python setup.py test
script:  
  - python run_tests.py
 
#after_sucess:
#  coveralls
