matrix:
  allow_failures:
    - os: osx
  include:
    - os: osx
      language: generic
    - os: linux
      language: python
      python: "3.5"
    - os: linux
      language: python
      python: "3.6"
#cache:
#  apt: true
#  directories:
#    - $HOME/miniconda

before_install:
  # install miniconda for Python dependencies
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda -f
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda config --set always_yes yes 
  - conda update --yes conda
  - conda config --add channels defaults
  - conda config --add channels bioconda
  - conda config --add channels conda-forge
  - conda info -a
  # if matplotlib functionality is tested
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ( sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok )& fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then ulimit -S -n 4096; ulimit -a; fi
install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      conda install python=$TRAVIS_PYTHON_VERSION pip future "numpy<1.14" scipy matplotlib=2 statsmodels scikit-learn seaborn jinja2 bedtools "pysam<0.11.2" pybedtools ucsc-genepredtobed lightning r xgboost pillow pyyaml diskcache six ucsc-bigbedtobed xdg python-xxhash readline ghostscript homer gadem trawler weeder xxmotif tqdm genomepy ncurses meme;
   else
      conda install python=3 pip future "numpy<1.14" scipy matplotlib=2 statsmodels scikit-learn seaborn jinja2 bedtools "pysam<0.11.2" pybedtools ucsc-genepredtobed lightning r xgboost pillow pyyaml diskcache six ucsc-bigbedtobed xdg python-xxhash readline ghostscript homer gadem trawler weeder xxmotif tqdm genomepy ncurses meme;
    fi
  - python setup.py build
  - pip install msgpack
#  - pip install coveralls
# # command to run tests, e.g. python setup.py test
script:  
  - python run_tests.py

#after_sucess:
#  coveralls
