language: python

python:
  - "2.7"

#cache:
#  apt: true
#  directories:
#    - $HOME/miniconda

before_install:
  # install miniconda for Python dependencies
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda -f
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda info -a
  # if matplotlib functionality is tested
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy matplotlib statsmodels pymc scikit-learn seaborn jinja2
  - conda install --yes -c bioconda python=$TRAVIS_PYTHON_VERSION bedtools pysam pybedtools ucsc-genepredtobed lightning
  - conda install --yes -c r r 
  - wget https://cran.r-project.org/src/contrib/RobustRankAggreg_1.1.tar.gz
  - R CMD INSTALL RobustRankAggreg_1.1.tar.gz
  - python setup.py develop
  - pip install .
#  - pip install nose coverage
#  - pip install coveralls
# # command to run tests, e.g. python setup.py test
script:  
  - python test/test_cluster.py
  - $HOME/miniconda/bin/python test/test_cluster.py
  - python run_tests.py
  - $HOME/miniconda/bin/python test/test_cluster.py

 
#after_sucess:
#  coveralls
