language: python

python:
  - "2.7"
  - "3.4"

cache:
  apt: true
  directories:
    - $HOME/miniconda

before_install:
  # install miniconda for Python dependencies
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda -f
  - export PATH=$HOME/miniconda/bin:$PATH
  - conda update --yes conda
  - conda config --add channels conda-forge
  - conda config --add channels defaults
  - conda config --add channels r
  - conda config --add channels bioconda
  - conda info -a
  # if matplotlib functionality is tested
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy matplotlib=2 statsmodels pymc scikit-learn 
  - conda install --yes python=$TRAVIS_PYTHON_VERSION seaborn jinja2 bedtools pysam pybedtools ucsc-genepredtobed 
  - conda install --yes python=$TRAVIS_PYTHON_VERSION lightning r xgboost r-robustrankaggreg ete3 pillow pyyaml meme diskcache six configparser
  - pip install xdg
  - pip install xxhash
  - python setup.py develop
  - python setup.py build
#  - pip install nose coverage
#  - pip install coveralls
# # command to run tests, e.g. python setup.py test
script:  
  - python run_tests.py

#after_sucess:
#  coveralls
